# Branch Protection Configuration
# This file defines branch protection rules
# Note: These rules need to be applied via GitHub API or manually in repository settings

branches:
  main:
    required_status_checks:
      strict: true
      contexts:
        - ci-build-test-lint
        - pr-validation
        - code-coverage
    enforce_admins: true
    required_pull_request_reviews:
      required_approving_review_count: 1
      dismiss_stale_reviews: true
      require_code_owner_reviews: true
      require_last_push_approval: false
    restrictions: null
    required_linear_history: false
    allow_force_pushes: false
    allow_deletions: false
    required_conversation_resolution: true
    lock_branch: false
    allow_fork_syncing: false
