//
//  AppColorPalette.swift
//  Disability Advocacy
//
//  Platform-specific color definitions and semantic colors
//
//  Note: Most colors are defined in Assets.xcassets and automatically
//  generated as Color properties. This file only defines colors that
//  need platform-specific implementations or aren't in the asset catalog.
//

import SwiftUI
#if os(macOS)
import AppKit
#else
import UIKit
#endif

extension Color {
    #if os(macOS)
    // macOS-specific color definitions (asset catalog colors are auto-generated)
    // Only define colors that differ from asset catalog defaults
    // Note: Accent colors (accentBlue, accentGreen, accentOrange, etc.) are
    // defined in Assets.xcassets and automatically generated by Xcode
    #else
    // iOS colors are automatically generated from asset catalog
    // Accent colors are also defined in asset catalog
    #endif

    // MARK: - Semantic Colors (Shared)
    static var semanticSuccess: Color { triadTertiary }
    static var semanticWarning: Color { triadSecondary }
    static var semanticError: Color { Color.red }
    static var semanticInfo: Color { triadPrimary }
    
    static var semanticSuccessBackground: Color { semanticSuccess.opacity(0.18) }
    static var semanticWarningBackground: Color { semanticWarning.opacity(0.18) }
    static var semanticErrorBackground: Color { semanticError.opacity(0.18) }
    static var semanticInfoBackground: Color { semanticInfo.opacity(0.18) }

    // MARK: - Triadic Color Scheme
    static var triadPrimary: Color { Color("accentPurple") }
    static var triadSecondary: Color { Color("accentOrange") }
    static var triadTertiary: Color { Color("accentGreen") }
}

extension ShapeStyle where Self == Color {
    static var triadPrimary: Color { .triadPrimary }
    static var triadSecondary: Color { .triadSecondary }
    static var triadTertiary: Color { .triadTertiary }
}

// MARK: - App Color Roles

/// Centralized semantic color roles backed by the asset catalog.
enum AppColors {
    static var background: Color { .appBackground }
    static var groupedBackground: Color { .groupedBackground }
    static var surface: Color { .cardBackground }
    static var surfaceSecondary: Color { .surfaceSecondary }
    static var surfaceElevated: Color { .surfaceElevated }

    static var textPrimary: Color { .primaryText }
    static var textSecondary: Color { .secondaryText }
    static var textTertiary: Color { .tertiaryText }

    static var separator: Color { Color("dividerColor") }
    static var border: Color { Color("borderColor") }
    
    static var primary: Color { .triadPrimary }
    static var secondary: Color { .triadSecondary }
    static var tertiary: Color { .triadTertiary }
}
